embedding_size: 128              # (int) The embedding size of users and items.
n_layers: 2                     # (int) The number of layers in LightGCN.
reg_weight: 1e-05               # (float) The L2 regularization weight.
input_dim: 128


analyze: False
sae_k: 44
sae_scale_size: 64
learning_rate:  1e-3
valid_metric: "NDCG@10"
steer: 0
"base_path": "./saved/sasrec_ml-1m.pth"
# "load": "./saved/sasrec_beer-32-52.pth"
"learning_rate": 1e-3
"alpha": 1.0
"steer": False
"metrics": ["NDCG", "GiniIndex", "ItemCoverageN"]
"input_dim": 128

